### ISSUE TITLE
Peticiones Multipart en Internet Explorer 9

### ISSUE THREAD

**Issue by laurapazos** [UDA-EJIE/udaLib#2]
Hemos detectado un problema a la hora de utilizar peticiones Multipart en Internet Explorer 9.

Como sabíamos, para el IE9, se utiliza un filtro que mapea peticiones que no sean GET y POST (estos navegadores no pueden hacerlo), al tipo indicado, en el parametro _method. 
El problema que tenemos es que al enviar una petición Multipart, funciona correctamente en el POST pero en la petición PUT pierde el valor del fichero.

El orden de los filtros implicados es el siguiente:

- MultipartFilter
- HiddenHttpMethodFilter

Hemos observado que en la petición PUT accede dos veces a UdaMultipartResolver.resolveMultipart(), perdiéndose en la segunda el contenido multipart de la petición.

La siguiente es la secuencia de acciones detectada:

- En el paso por MultipartFilter se llama a UdaMultipartResolver, donde se resuelven los valores correctos del contenido multipart de la request.
- En el paso por HiddenHttpMethodFilter se enmascara la petición en una HttpServletRequestWrapper para simular los métodos HTTP.
- En el DispatcherServlet comprueba si es una instancia de MultipartHttpServletRequest, pero no detecta el HttpServletRequestWrapper (lo hace a partir de Spring 3.2.11 [1][2]) , por lo que vuelve a llamar UdaMultipartResolver, que falla al resolver los valores del contenido multipart.

Como decimos, el problema es de Spring, que ya lo soluciona en una versión posterior, pero permanece en los proyectos de UDA por la versión de Spring elegida.
Se nos ocurren dos soluciones:
- Actualizar la versión de Spring a una posterior el parche
- Modificar UdaMultipartResolver para que detecte los Wrapper y, con un nuevo Wrapper, devuelva los datos multipart previamente resueltos.

[1] https://jira.spring.io/browse/SPR-12114
[2] https://github.com/spring-projects/spring-framework/commit/7cf4a4ed2daaf896605bf1192060a131ea72b2ef

**Comment by sergisu** [comment]
Hola, 

Probaremos la secuencia de acciones que nos reportas en la nueva versión que estamos desarrollando. 
Y os informaremos de forma conveniente.

Muchas gracias.

UDA

**Comment by uGuinea** [comment]
Hola: 
Hemos confirmado el error detectado. En la versión 3.0 de UDA, que está a punto de salir, ya integramos las librerías de Spring 3.2.17, donde el error se ha solucionado y efectivamente no hay problemas con las peticiones PUT para la subida de ficheros.
Por lo que, desde el equipo de desarrollo de UDA , aclaramos que si se desea realizar subidas de ficheros por PUT, hay que usar UDA 3.0 , en  UDA 2.x no vamos a dar soporte a esa funcionalidad, tan solo para peticiones POST.
