### ISSUE TITLE
Publicación de versiones 5.0.x en el repositorio de EJIE

### ISSUE THREAD

**Issue by ihernaez** [UDA-EJIE/udaLib#25]
En el [repositorio de EJIE](http://repository.ejiedes.net/index.html#nexus-search;quick~x38ShLibClasses) aún no se han publicado las versiones 5.0.0 y 5.0.1 de las librerías de UDA (Lo mismo qué pasó en #4).
Las versiones son demasiado recientes para que aplicaciones las estén usando, pero por prevenir.

**Comment by ihernaez** [comment]
Se han publicado las versiones 5.0.0 y 5.0.1 de los artefactos `com.ejie.x38:x38ShLibClasses`, `com.ejie.x38:x38ShLibClasses-rup` y `com.ejie.x38:x38ShLibClasses-hdiv`, pero quedan pendientes los artefactos `com.ejie.x38:x38ShLibClasses-dav`, `com.ejie.x38:x38ShLibClasses-pif` y `com.ejie.x38:x38ShLibClasses-cache`.

Además los artefactos `com.ejie.x38:x38ShLibClasses` contienen los packages `com.ejie.x38.hdiv.*`, que según el fichero [build.xml](https://github.com/UDA-EJIE/udaLib/blob/v5.0.1/x38ShLibClasses/build.xml) deberían estar excluidos ya que van en `com.ejie.x38:x38ShLibClasses-hdiv`.

**Comment by xaabi6** [comment]
Hola @ihernaez, sí, faltan por publicar algunas de las librerías, intentaremos subirlas pronto.

Respecto a lo segundo, gracias por el aviso, le echaremos un ojo para solventarlo porque es cierto que el artefacto `com.ejie.x38:x38ShLibClasses` no debería contener los paquetes de `com.ejie.x38.hdiv.*`.

**Comment by xaabi6** [comment]
Hola @ihernaez, ya está corregida la exclusión de las clases en los artefactos. Nos queda pendiente la subida de las librerías.

**Comment by ihernaez** [comment]
:+1:
