### ISSUE TITLE
Acciones sobre tablas al tener un elemento seleccionado

### ISSUE THREAD

**Issue by jalvarez1983** [UDA-EJIE/udaLib#26]
Hola,

A partir de la versión 5.0.1 de UDA, al realizar acciones sobre una tabla (filtro, limpiar filtro, paginación) si hay algún elemento seleccionado, se está produciendo un error:

![image](https://user-images.githubusercontent.com/2207608/147232916-712dfbfd-3da1-4498-a1e3-6c6978d59277.png)

Se puede reproducir el error en la app de ejemplo (actualmente está la versión 5.0.2).

El error se produce al hacer el filtro, parece que se debe a la anotación TrustAssertion que se encuentra en la clase embebida Multiselection de TableRequestDto.

![image](https://user-images.githubusercontent.com/2207608/147233268-9a6f9589-cc4e-49f8-8d26-0a7a0da41354.png)

![image](https://user-images.githubusercontent.com/2207608/147233177-ed0f97b7-4429-42ac-83b0-3d68e6faceba.png)

Gracias!

**Comment by xaabi6** [comment]
Hola @jalvarez1983, el error que comentas sucede por un problema con el agente de Hdiv cuyo origen es conocido y es ajeno a UDA. Está pendiente de ser aplicada una corrección para que comience a funcionar correctamente.

Cabe decir que este problema no afecta a las aplicaciones que se encuentren en un entorno local o externo a EJIE.

**Comment by jalvarez1983** [comment]
Eskerrik asko @xaabi6 .

Como posible mejora, igual en el documentación de integración con Hdiv se podría indicar que es necesario tener el agente instalado (en local y en los servidores donde se vaya a desplegar).

**Comment by xaabi6** [comment]
Técnicamente hablando @jalvarez1983, no es necesario instalar el agente para que funcione, aunque sí que es totalmente recomendable hacerlo porque cuando se usan ambos (agente y librería), se obtiene la mayor protección posible:
![imagen](https://user-images.githubusercontent.com/22637294/147643002-6752490d-f732-4bb6-8fc9-9428b5e7c0ab.png)

**Comment by jalvarez1983** [comment]
Pues entonces seguimos teniendo algo mal, porque si arranco el server sin el agente de Hdiv no me cifra los ids y se producen los errores.

**Comment by xaabi6** [comment]
Eso os sucede porque no está obteniendo la licencia, en los logs de WebLogic te lo debería de estar indicando.

La licencia viene incluida con el agente y se obtiene al importar el script `setHdiv` en `startWebLogic`. Si no se va a usar el agente, hay que eliminar mínimo la siguiente línea en el script `setHdiv` (se encarga de la inicialización del agente):
```shell
set JAVA_OPTIONS=%JAVA_OPTIONS% -javaagent:%HDIV_LOCAL_DIR%/hdiv-ee-agent.jar
```

**Comment by jalvarez1983** [comment]
Gracias @xaabi6 

Hasta ahora para no usar el agente comentábamos directamente la importación del setHdiv en el startWebLogic, he probado a eliminar la línea en el script. manteniendo las demás opciones y comprobando que no se producen errores de licencia,  pero me sigue pasando lo mismo, no me cifra los ids.

![image](https://user-images.githubusercontent.com/2207608/147650920-c015e2da-913c-461e-9f3f-b95a58f041db.png)

![image](https://user-images.githubusercontent.com/2207608/147651023-af2d5a7c-7366-4471-9a1a-da3325932c6a.png)


De todas formas no te quiero hacer perder mas el tiempo, sabiendo que con el agente nos vale de momento suficiente.

Eskerrik asko.
