### ISSUE TITLE
Problema definición ExceptionHandler en versión 5.0.3

### ISSUE THREAD

**Issue by jalvarez1983** [UDA-EJIE/udaLib#29]
Hola,

Con la nueva versión de UDA (5.0.3) la definición de handlers propios para el manejo de excepciones no está funcionando, nos esta redirigiendo directamente a la página de error (es un proyecto generado de 0, con el plugin de UDA y con las librerías definidas en el pom, sin añadir ninguna).

Ej definición del handler:

![image](https://user-images.githubusercontent.com/2207608/171563660-0226b2b7-f759-4c1a-a138-e94d0342a76f.png)

En versiones anteriores (5.0.1 y 5.0.2) está funcionando correctamente. 
Si eliminamos del web.xml las referencias de HDIV y quitamos la clase UDA4HdivConfig vuelve a funcionar correctamente.

Muchas gracias,
Un saludo.

**Comment by hmartinez85** [comment]
Buenas, para la versión actual , la clase a usar es la
com.ejie.x38.hdiv.config.WebConfig

Se puede ver en esta documentación, punto 6.5:
[wiki uda y hdiv](https://github.com/UDA-EJIE/uda-ejie.github.io/wiki/Hdiv)

Un saludo.

**Comment by jalvarez1983** [comment]
Muchas gracias! Perdonar que no había leído la documentación. Ahora funciona perfectamente.

Viendo el commit de @xaabi6 os he abierto una PR en udaTemplates para cambiar también el bean multipartResolver por el Hdiv.

Un saludo.

**Comment by hmartinez85** [comment]
Perfecto @jalvarez1983 , muchas gracias, un saludo.
