### ISSUE TITLE
Error en mock xlnets

### ISSUE THREAD

**Issue by ma-santamaria** [UDA-EJIE/udaLib#35]
Estamos intentando hacer uso del mock de xlnets para desarrollar una nueva aplicación pero nos hemos encontrado con el siguiente problema tras activarlo como se indica en la documentación:

```
java.net.MalformedURLException

no protocol: /ae24aRegiaWar/mockLoginPage?mockUrl=http://localhost:7001/ae24aRegiaWar

java.net.URL.(URL.java:593)
java.net.URL.(URL.java:490)
java.net.URL.(URL.java:439)
weblogic.servlet.internal.ServletResponseImpl.sendRedirect(ServletResponseImpl.java:992)
weblogic.servlet.internal.ServletResponseImpl.sendRedirect(ServletResponseImpl.java:975)
javax.servlet.http.HttpServletResponseWrapper.sendRedirect(HttpServletResponseWrapper.java:176)
org.hdiv.ee.init.EEResponseWrapper.sendRedirect(EEResponseWrapper.java:34)
javax.servlet.http.HttpServletResponseWrapper.sendRedirect(HttpServletResponseWrapper.java:176)
org.springframework.security.web.firewall.FirewalledResponse.sendRedirect(FirewalledResponse.java:44)
com.ejie.x38.security.MyAuthenticationEntryPoint.commence(MyAuthenticationEntryPoint.java:112)
org.springframework.security.web.access.ExceptionTranslationFilter.sendStartAuthentication(ExceptionTranslationFilter.java:203)
org.springframework.security.web.access.ExceptionTranslationFilter.handleSpringSecurityException(ExceptionTranslationFilter.java:167)
org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:133)
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
```

Parece que la redirección que se intenta hacer tras leer los usuarios configurados en el security-config.xml no se realiza correctamente.

A parte de definir el perimetralSecurityWrapper como se indica en la documentación ¿es necesario realizar alguna configuración extra en la aplicación o en weblogic para que el mock funcione?

**Comment by Banji0x** [comment]
It seems that the redirection being attempted after reading the configured users in the security-config.xml file is not being performed correctly.

**Comment by escaleramen** [comment]
El problema viene dado porque el weblogic se niega a hacer un sendRedirect con una ruta relativa (sin el host y el puerto). 

Actualmente el método "commence" de la clase  "com.ejie.x38.security.MyAuthenticationEntryPoint" realiza la redirección a la pagina de login del mock mediante un "httpResponse.sendRedirect(url);" con una ruta relativa ("/xxxyyyyyWar/mockLoginPage?mockUrl=..."). Este modo de redirección, parece, que al nuevo servidor no le gusta y levanta una excepcion de tipo "java.net.MalformedURLException". 

He estado probando algún parámetro del weblogic.xml, "redirect-with-absolute-url", para especificarle que permita el uso de url's relativas, pero parece no terminarle de gustar. Quizá habría una solución por ese lado pero no hemos llegado a dar con ella.

La solución que si funciona es actualizar  el método "commence" de la clase  "com.ejie.x38.security.MyAuthenticationEntryPoint" para que no use una url relativa,, sino una absoluta extraída de la propia petición. 

cambiando la línea de código: 
               httpResponse.sendRedirect(url);
por:
               URL urlAdsoluta = new URL(httpRequest.getScheme(), httpRequest.getServerName(),  httpRequest.getServerPort(), url);
	       logger.info("Redirecting to next URL:" + urlAdsoluta);
	       httpResponse.sendRedirect(urlAdsoluta.toString());

el error deja de producirse.

**Comment by ma-santamaria** [comment]
También habíamos probado modificando las configuraciones dentro de weblogic.xml pero con el mismo resultado. Por lo que comentas entendemos que el problema se solucionará para siguientes versiones de uda, ¿correcto?

**Comment by xaabi6** [comment]
Perdonad la demora, pero ya he podido probarlo y efectivamente estaba fallando.

La solución propuesta por @escaleramen funciona correctamente, aunque tiene un pero, cuando no se usa el mock provoca un error porque genera la siguiente URL: 

> https://desarrollo.jakina.ejiedes.net:8111https://xlnets.servicios.des.ejgv.euskalsarea.eus/n38a/N38LoginInicioServlet?N38API=https://desarrollo.jakina.ejiedes.net:8111/x21aAppWar/iberdok/view

A pesar de esto, ha sido sencillo controlarlo con una pequeña condición que he probado tanto con el mock como con el wrapper de N38 y con ambos funciona bien, así que en la siguiente versión que liberemos estará presente la corrección.
