### ISSUE TITLE
Enviar formulario con rupSelect precargados por ajax

### ISSUE THREAD

**Issue by JONAGUIPER** [UDA-EJIE/udaLib#36]
Actualmente tenemos una entidad (PrimeraSolicitudDTO) asociada a un formulario, la cual posee una subentidad (Paciente) que contiene valores de en ubicación que se obtienen mediante NORA:

![image](https://github.com/UDA-EJIE/udaLib/assets/14790146/29a0081f-a07a-43ca-a2e0-5c6d0b660df1)

Todas las entidades de Nora están con la notación: SecureIdentifiable<String (con la clase correspondiente)> 

Al cargar el formulario se tiene la posibilidad que introduciendo el dni del mismo se puedan precargar los datos asociados al mismo.
![image](https://github.com/UDA-EJIE/udaLib/assets/14790146/09d78394-9c2b-4696-bfb1-d5257b1df129)

Cuando esto ocurre en el mapa: SERVER_SIDE_MAP se almacenan los valores del formulario permitidos, Por ejemplo:
![image](https://github.com/UDA-EJIE/udaLib/assets/14790146/11616ca9-c1e7-4a7e-8d1f-af6264507f70)

El problema está en que si por algún casual se cambia el valor de alguno de los valores de los select que se cargan de manera remota la petición devuelve un error:
![image](https://github.com/UDA-EJIE/udaLib/assets/14790146/9662b03a-93e4-4a73-b417-76ac8b9a291a)

La petición realizada fue:
![image](https://github.com/UDA-EJIE/udaLib/assets/14790146/7568ea1a-34de-4c42-a165-d06f5374f637)

En este caso se cambio el numero del portal y es la petición que falla. ya que no está registrada como un valor válido.

Entiendo que debería registrarse o permitir los valores que se precargaron en los select... no he podido encontrar la manera que esto sea posible.

**Comment by xaabi6** [comment]
Se cierra la issue porque se tomó la decisión de abandonar el proyecto udaHdiv en favor de otras soluciones. Disculpa las molestias.
