### ISSUE TITLE
Problemas con llamada con entidad no registrada

### ISSUE THREAD

**Issue by JONAGUIPER** [UDA-EJIE/udaLib#37]
Tenemos una pagina que se pinta mediante jsp y tiene un listado según se muestra:
![image](https://github.com/UDA-EJIE/udaLib/assets/14790146/a2cf464b-a6da-4100-a22d-b8ab43e362d3)

Como se ven los botones son Anclas que se generan mediante <spring:url>:
![image](https://github.com/UDA-EJIE/udaLib/assets/14790146/5a8c5010-81da-4f4c-8959-c3353f443cbf)

Al llegar al detale de la solicitud, se muestra la Pantalla que tiene un formulario para editar la entidad asociada a este mismo detalle. (izquierda)
Revisamos los datos de la Sesión y podemos observar que no se encuentra esta entidad para poder editarla: (derecha)
![image](https://github.com/UDA-EJIE/udaLib/assets/14790146/79c3e940-42f9-477b-ac2e-57da8b477154)

La llamada al editar el formulario es:
![image](https://github.com/UDA-EJIE/udaLib/assets/14790146/cdf94105-ea43-444d-9462-cf06017887ab)

En el controller agregamos los datos necesarios para este formulario:
![image](https://github.com/UDA-EJIE/udaLib/assets/14790146/cc60d444-dfbc-434c-8184-4a44aa91e20f)

Muchisimas gracias por toda la ayuda que nos puedan prestar

**Comment by xaabi6** [comment]
Se cierra la issue porque se tomó la decisión de abandonar el proyecto udaHdiv en favor de otras soluciones. Disculpa las molestias.
