### ISSUE TITLE
Controller no mapeados

### ISSUE THREAD

**Issue by JONAGUIPER** [UDA-EJIE/udaLib#38]
Actualmente estamos teniendo un problema al acceder a ciertos controllers despues de hacer un despliegue tanto en local como en Desarrollocon la siguiente traza:
![image](https://github.com/UDA-EJIE/udaLib/assets/14790146/9514bb06-e2ce-4b0c-b478-169dfca476e0)

Al intentar ver el código observamos que la linea es:
![image](https://github.com/UDA-EJIE/udaLib/assets/14790146/0e2a6a59-c97a-4372-ab3e-80580a064cda)

Al ir mas adentro encontramos que:
![image](https://github.com/UDA-EJIE/udaLib/assets/14790146/167dab59-e243-4748-98c3-2419eaec3953)
tenemos una excepción sin controlar y que ademas no el valor por defecto es null lo que hace que el toEstring de un fallo por lo tanto no podemos saber si el error es este o que el método del controlloer no se encuentra bien definido (aunque está como todos los demás)

Hemos descubierto en local que después de cambiar algo en algún controller relacionado con un espacio en un comentario o algo, republicamos la app y ya no da este error. Pero en desarrollo este error parece reproducirse y en este punto no podemos republicar.

Gracias por toda la colaboración que puedan prestar.

**Comment by xaabi6** [comment]
Gracias por el aviso @JONAGUIPER, [he incluido una traza](https://github.com/UDA-EJIE/udaLib/commit/9893ceb29f09148d207ccb9ea8022e83a7bbf7a9) para que capture la excepción en los logs y al menos podamos tener más información sobre el fallo.

**Comment by JONAGUIPER** [comment]
probado no llega ni a ese punto ya en el if la [variable](https://github.com/UDA-EJIE/udaLib/commit/9893ceb29f09148d207ccb9ea8022e83a7bbf7a9#commitcomment-120580275) viene nula

**Comment by xaabi6** [comment]
Entiendo, gracias por la información, le echaré un vistazo.

**Comment by xaabi6** [comment]
Se cierra la issue porque se tomó la decisión de abandonar el proyecto udaHdiv en favor de otras soluciones. Disculpa las molestias.
