### ISSUE TITLE
Formulario sencillo si poder hacer Update

### ISSUE THREAD

**Issue by JONAGUIPER** [UDA-EJIE/udaLib#39]
Tenemos este formulario bastante sencillo: 
![image](https://github.com/UDA-EJIE/udaLib/assets/14790146/6b3b6cef-3aa8-4809-bbb8-829cdfde41a2)
el campo dni lo ocultamos con un hidden ya que es el id de la clase:
![image](https://github.com/UDA-EJIE/udaLib/assets/14790146/1d29ed86-daec-47da-ad78-847bbfa2c216)
al tratar de enviar el formulario tnemos el siguiente error:
JSON parse error: Not allowed identifier; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Not allowed identifier (through reference chain: com.ejie.ad97a.model.Medico[\"dni\"])"
![image](https://github.com/UDA-EJIE/udaLib/assets/14790146/6690afe6-aab1-42aa-b641-652af306d0ff)
según vemos parece que no se envía el nid por lo que creemos que es la causa del problema.

En este caso el jsp lo tenemos de la siguiente manera:
![image](https://github.com/UDA-EJIE/udaLib/assets/14790146/6d1c15f2-3a43-44d6-a82c-c2004054bad1)

Hemos eliminado toda llamada ajax para evitar problemas pero aún así no le hacemos funcionar.
los controller son:
![image](https://github.com/UDA-EJIE/udaLib/assets/14790146/01a137fd-b326-466c-87fb-f58ac4a8532e)

**Comment by xaabi6** [comment]
Se cierra la issue porque se tomó la decisión de abandonar el proyecto udaHdiv en favor de otras soluciones. Disculpa las molestias.
