### ISSUE TITLE
Publicación de la versión 2.4.7 en el repositorio de EJIE

### ISSUE THREAD

**Issue by ihernaez** [UDA-EJIE/udaLib#4]
En el [repositorio de EJIE](http://repository.ejiedes.net/index.html#nexus-search;quick~x38ShLibClasses) aún no se ha publicado la versión 2.4.7 de las librerías de UDA, publicada el 31-Mayo-2016, y las aplicaciones de migradas a esa versión no pueden encontrar las dependencias durante los traspasos.

**Comment by sergisu** [comment]
Se ha actualizado el repositorio Nexus con la versión 2.4.7 de las librerías.
Perdonad las molestias.

UDA

![image](https://cloud.githubusercontent.com/assets/11539034/22559513/9f6e8970-e971-11e6-83a7-c4ce84b565db.png)
