### ISSUE TITLE
Los modelos solo permiten incluir un único parámetro con TrustAssertion

### ISSUE THREAD

**Issue by sergeisg** [UDA-EJIE/udaLib#40]
Buenas!

Voy a ilustrar este caso específico con un ejemplo para que se entienda mejor. Tenemos un modelo, Notificación. Este modelo tiene un TrustAssertion en su propio id, idNotif, y otro en el id de las solicitudes con las que está relacionado, idSolicitud. 

![Screenshot_37](https://github.com/UDA-EJIE/udaLib/assets/91953689/268db90b-06d9-425f-923c-75e6aeb37e8c)

Necesitábamos pasar los datos al controller para añadirlos al modelo para utilizarlos en el jsp. 

![Screenshot_41](https://github.com/UDA-EJIE/udaLib/assets/91953689/22741b12-ddb5-414e-af74-1899a13fef0f)

A primera vista, la url parecía correcta con el id encriptado pero a la hora de hacer la petición get, siempre fallaba. 

Al deofuscar el id encriptado de la solicitud, se descubrió que mientras el id desencriptado correspondiente era correcto, se atribuía ese id a la clase Notificación, y no a la clase Solicitud como debería. Por tanto, al intentar hacer un /get/{id} con ese id encriptado, la petición siempre fallaba.

Para poder resolver esto de manera temporal y poder trabajar, se ha procedido a implementar un HashMap, que relacione los ids de las notificaciones con los ids de las solicitudes. Para ello, en el jsp, se referenciaria ese mapa cuando necesitasemos obtener el id de la solicitud con la encriptación necesaria. 

![Screenshot_39](https://github.com/UDA-EJIE/udaLib/assets/91953689/c7997d09-0893-4acf-a6f8-9c2427a6d26e)

![Screenshot_38](https://github.com/UDA-EJIE/udaLib/assets/91953689/5f451b0d-60b4-4b22-a995-619d3f036256)

Pero entendemos que se debería poder encriptar todas los parámetros indicados con el TrustAssertion en el modelo y funcionar simplemente haciendo esto:

![Screenshot_41](https://github.com/UDA-EJIE/udaLib/assets/91953689/22741b12-ddb5-414e-af74-1899a13fef0f)

Un saludo y muchas gracias.

**Comment by xaabi6** [comment]
Se cierra la issue porque se tomó la decisión de abandonar el proyecto udaHdiv en favor de otras soluciones. Disculpa las molestias.
